Update aws_deploy.yml

diff --git a/.github/workflows/aws_deploy.yml b/.github/workflows/aws_deploy.yml
--- a/.github/workflows/aws_deploy.yml
+++ b/.github/workflows/aws_deploy.yml
@@ -31,6 +31,10 @@ jobs:
           git reset --hard || { echo "Error: Failed to reset repository."; exit 1; }
           git pull https://${{ secrets.PAT_TOKEN }}@github.com/hariharan2604/PostInvest-Pro.git || { echo "Error: Failed to pull latest changes."; exit 1; }
 
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          nvm use --lts || { echo "Error: Failed to use LTS version of Node.js."; exit 1; }
+
           echo "Installing dependencies..."
           npm install || { echo "Error: Failed to install dependencies."; exit 1; }
 
